### PR TITLE
Add setuptools installation instruction

### PR DESCRIPTION
**Pull request by Flaburgan**
As the plugin needs it ;)

### CODE REVIEW

**Comment by Flaburgan** [comment]
Hm, visiblement en tant que tel ca suffit pas, j'ai d'autres erreurs quand j'essaye d'installer le plugin: https://gist.github.com/Flaburgan/10fc983d79107c3e664bbf3a45d990c1

**Comment by Flaburgan** [comment]
Looks like it also needs `pip install wheel`, but that's still not enough:
```
...
  running build_ext
  building '_geohash' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYTHON_MODULE=1 -I/usr/include/python2.7 -c src/geohash.cpp -o build/temp.linux-x86_64-2.7/src/geohash.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/geohash.cpp:538:20: fatal error: Python.h: Aucun fichier ou dossier de ce type
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-geohash
  Running setup.py clean for python-geohash
Successfully built addok-trigrams addok
Failed to build python-geohash
Installing collected packages: python-geohash, redis, addok, addok-trigrams
  Running setup.py install for python-geohash ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KUAOnc/python-geohash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rgoDbk-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying geohash.py -> build/lib.linux-x86_64-2.7
    copying quadtree.py -> build/lib.linux-x86_64-2.7
    copying jpgrid.py -> build/lib.linux-x86_64-2.7
    copying jpiarea.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_geohash' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYTHON_MODULE=1 -I/usr/include/python2.7 -c src/geohash.cpp -o build/temp.linux-x86_64-2.7/src/geohash.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/geohash.cpp:538:20: fatal error: Python.h: Aucun fichier ou dossier de ce type
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KUAOnc/python-geohash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rgoDbk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-KUAOnc/python-geohash/
(maps2)root@maps2:/etc/addok# 
```

**Comment by yohanboniface** [comment]
You need `python-dev` package it seems (may be named `python3-dev` according to your distro and it's flavour).

**Comment by Flaburgan** [comment]
Closing this at the moment, as I was messing things being inside and outside the venv. I'll reopen it with the correct instructions if I try to install the plugin again.

**Pull request closed without merging**
